# 机器人设置
bot_settings:
  # 类型
  # qqbot
  # onebot
  type: "onebot"
  # 官方机器人
  qq_bot:
    # 机器人QQ
    qq: 0
    # 机器人ID
    app_id: ""
    # 机器人令牌
    token: ""
    # 机器人密钥
    secret: ""
    # 接口服务
    web_hook:
      # 端口
      port: 8443
      # 默认文件URL格式
      default_file_url_format: "http://127.0.0.1:8443/file/get?path={name}"
      # ssl设置(jks格式)
      ssl:
        # 开关
        enable: false
        # 别名
        alias: ""
        # 文件
        file: ""
        # 密钥
        key: ""

  # OneBot
  one_bot:
    # WebSocket地址 (末尾必须为/)
    websocket_host: "ws://127.0.0.1:3001/"
    # HTTP地址 (末尾必须为/)
    http_host: "http://127.0.0.1:3000/"
    # 鉴权
    # access_token: ""

# Minecraft-WebSocket服务器设置
minecraft_websocket_settings:
  # 端口
  port: 5835

# 日志设置
log_settings:
  # 群聊消息
  group: true
  # 私聊消息
  private: true
  # WebHook服务端消息
  web_hook: true