<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>cn.chengzhiya</groupId>
        <artifactId>mhdfbot</artifactId>
        <version>2.1.7</version>
    </parent>
    <artifactId>mhdf-bot-pluginexample</artifactId>

    <build>
        <finalName>[梦之机器人-插件示例]${project.artifactId}-${project.version}</finalName>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>3.6.0</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <createDependencyReducedPom>false</createDependencyReducedPom>
                            <filters>
                                <filter>
                                    <artifact>*:*</artifact>
                                    <excludes>
                                        <exclude>META-INF/</exclude>
                                        <exclude>schema/</exclude>
                                    </excludes>
                                </filter>
                            </filters>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-deploy-plugin</artifactId>
                <version>2.8.2</version>
                <configuration>
                    <skip>true</skip>
                </configuration>
            </plugin>
        </plugins>

        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>true</filtering>
            </resource>
        </resources>
    </build>

    <repositories>
        <repository>
            <id>chengzhimeow-maven-repo-releases</id>
            <name>橙汁喵の仓库</name>
            <url>https://maven.chengzhimeow.cn/releases</url>
        </repository>
    </repositories>

    <dependencies>
        <dependency>
            <groupId>cn.chengzhiya</groupId>
            <artifactId>mhdf-bot-api</artifactId>
            <version>2.1.7</version>
            <scope>provided</scope>
        </dependency>
    </dependencies>
</project>
