name: MHDF-Bot-PluginExample
version: 1.0.0
main: cn.chengzhiya.mhdfbotpluginexample.Main
authors: [ ChengZhiYa ]
# support_framework: [ onebot, qqbot ]
# mhdfbot_version: 2.1.7
# depend: [ ciallo-plugin ]
# softdepend: [ zako-plugin ]
